server:
  additionalApplications:
    - name: ngnix-ingress-controller
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/artemio77/grockstock.git
        targetRevision: HEAD
        path: deploy/infrastructure/ngnix-ingress-controller
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
  ingress:
    enabled: true
    hosts:
      - argocd.k8s.aderevets