server:
  configEnabled: true
  config:
    repositories: |
      - type: git
        url: https://github.com/artemio77/grockstock.git
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
  additionalApplications:
    - name: infrastructure/nginx-ingress-controller
      namespace: nginx-ingress-controller
      destination:
        namespace: nginx-ingress-controller
        server: https://kubernetes.default.svc
      project: nginx-ingress-controller
      source:
        path: deploy/infrastructure/nginx-ingress-controller
        repoURL: https://github.com/artemio77/grockstock.git
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
  additionalProjects:
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
        - '*'
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
