apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: nginx-ingress-controller
spec:
  project: infrastructure
  destination:
    namespace: nginx-ingress-controller   #update namespace name if you wish
    name: k8s.aderevets   #update cluster name if its different
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.4.0"
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            type: ClusterIP