redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicaCount: 2

configs:
  dex.config: |
    connectors:
          - type: oidc
            id: okta
            name: Okta
            config:
              issuer: https://dev-604298.okta.com/oauth2/ausdgjmf773mCaE6w4x7
              clientID: 0oadgdk3yg7pLVkoF4x7
              clientSecret: voz6RpvdX2BIZwAw9PagGjD6zbRvS2m6VoPWRuc1